name:                learnopengl-haskell
version:             0.1.0.0
github:              "Autonym8/learnopengl-haskell"
license:             BSD3
author:              "Alice Rixte"
maintainer:          "alice.rixteøu@bordeaux.fr"
copyright:           "Alice Rixte"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Autonym8/learnopengl-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- OpenGL
- gl
- sdl2
- vector
- bytestring
- linear
- JuicyPixels
- JuicyPixels-extra
- lens
- pandia-base
- random
- mtl

when:
  - condition: os(windows)
    ghc-options: -optl-mconsole

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src


executables:
  hello-window:
    main:                Main.hs
    source-dirs:         app/1-Getting-started/4-hello-window/opengl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  hello-window-gl:
    main:                Main.hs
    source-dirs:         app/1-Getting-started/4-hello-window/gl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  hello-triangle:
    main:                Main.hs
    source-dirs:         app/1-Getting-started/5-hello-triangle/opengl
    ghc-options:
    - -optl-mconsole
    - -optl-mwindows
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  hello-triangle-simpler:
    main:                simpler.hs
    source-dirs:         app/1-Getting-started/5-hello-triangle/opengl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  hello-triangle-primitive:
    main:                primitive.hs
    source-dirs:         app/1-Getting-started/5-hello-triangle/opengl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  hello-triangle-gl:
    main:                 Main.hs
    source-dirs:          app/1-Getting-started/5-hello-triangle/gl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  square:
    main:                 square.hs
    source-dirs:          app/1-Getting-started/5-hello-triangle/gl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  shaders:
    main:                 Main.hs
    source-dirs:          app/1-Getting-started/6-shaders/gl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  textures:
    main:                 Main.hs
    source-dirs:          app/1-Getting-started/7-textures/gl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  transformations:
    main:                 Main.hs
    source-dirs:          app/1-Getting-started/8-transformations/gl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  coordinates:
    main:                 Main.hs
    source-dirs:          app/1-Getting-started/9-coordinates/gl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  camera:
    main:                 Main.hs
    source-dirs:          app/1-Getting-started/10-camera/gl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  colors:
    main:                 Main.hs
    source-dirs:          app/2-lighting/12-colors/gl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  basic-lighting:
    main:                 Main.hs
    source-dirs:          app/2-lighting/13-basic-lighting/gl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  materials:
    main:                 Main.hs
    source-dirs:          app/2-lighting/14-materials/gl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  lighting-maps:
    main:                 Main.hs
    source-dirs:          app/2-lighting/15-lighting-maps/gl
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell


tests:
  learnopengl-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
