name:                learnopengl-haskell
version:             0.1.0.0
github:              "Autonym8/learnopengl-haskell"
license:             BSD3
author:              "Alice Rixte"
maintainer:          "alice.rixteøu@bordeaux.fr"
copyright:           "Alice Rixte"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Autonym8/learnopengl-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- OpenGL
- sdl2
- vector
- bytestring
- linear

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hellowindow:
    main:                Main.hs
    source-dirs:         app/hellowindow
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  hellotriangle:
    main:                Main.hs
    source-dirs:         app/hellotriangle
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
  simpletriangle:
    main:                Main.hs
    source-dirs:         app/simpletriangle
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell


tests:
  learnopengl-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learnopengl-haskell
